server:
  port: "8080"
  mode: "debug" # debug | release | test

database:
  host: "127.0.0.1"
  port: 5432
  user: "postgres"
  password: "Wy050427!"
  dbname: "amiya-eden"
  sslmode: "disable"
  max_idle_conns: 10
  max_open_conns: 100

log:
  level: "debug"          # debug | info | warn | error
  filename: "logs/app.log"
  max_size: 100           # 单文件最大 100MB
  max_backups: 7          # 最多保留 7 个备份
  max_age: 30             # 最多保留 30 天
  compress: true          # 压缩旧文件

jwt:
  secret: "change_me_in_production"
  expire_day: 7

redis:
  addr: "127.0.0.1:6379"
  password: ""          # 无密码留空
  db: 0                 # 使用默认 DB
  pool_size: 10         # 连接池大小

eve_sso:
  client_id: "44fbbf1270ce427e8df49903b7e83729"          # EVE 开发者控制台申请的 Client ID
  client_secret: "TD70Lr81Ql7o3Sq7E56YitgRBTKQQKcxDmqhenoA"  # EVE 开发者控制台申请的 Client Secret
  callback_url: "http://localhost:8080/api/v1/sso/eve/callback"

sde:
  api_key: "change_me_sde_api_key"  # 用于保护 SDE 数据查询接口的 API Key
  proxy: "http://127.0.0.1:7890"    # 下载 SDE 时使用的代理，例如 http://127.0.0.1:7890 或 socks5://127.0.0.1:1080，留空不使用
  download_url: "https://api.github.com/repos/garveen/eve-sde-converter/releases/latest"  # SDE 数据下载 URL，默认为 GitHub API 获取最新 release 信息

app:
  allow_corporations: [98575144] # 允许访问的公司 ID 列表，空表示不限制

alliance_pap:
  base_url: "http://jp.newdoublex.space:25220"  # 联盟 PAP API 地址
  api_key: "n4QTCroEePpRaEUyVaHAd161hNmhRD"       # 联盟 PAP API Key